# cron 表达式 精确到秒 每天早上10点执行
Cron = ['0 0 6 * * *', '0 0 18 * * *']
Sort = 'time' # 排序方式 time: 按时间排序, default: 默认排序(根据website配置的网站顺序排序)

# API服务
[Api]
Domain = "" # API服务的域名,即通过点击这个域名即可访问到API服务
Port = 5050 # 端口

# 数据存储
[DB]
FileName = "db/bolt.db"

# 爬虫
[Spider]
WebSite = ["https://www.douban.com/group/szsh/discussion"] # 定义爬取的网站,可多个
TimeLimit = 5 # 定义爬取的时间限制 /天

[CookieCloud]
ServerHost = "https://cookiecloud.shroot.dev"
UUID = ""
Password = ""

# 数据清洗
[DataClean]
BlackList = ["合租", "求", "找", "盐田", "龙岗", "坪山", "大鹏", "宝安", "光明", "单间", "一室", "一房", "女生"]

[Logger]
Level = "debug"
Formatter = "text" # log 输出格式 text 或 json
Path = "logs/run.log"

# 通知
[Notice]
[Notice.WxPusher]
Enable = false #是否开启
AppToken = '' # 微信推送的AppToken
Uids = [] # 微信推送的UID
[Notice.Email]
Enable = true # 是否开启
From = '豆瓣房源爬虫 <notice@shroot.dev>' # 邮件发送人
User = 'notice@shroot.dev' # 邮箱账号
Pwd = '' # 邮箱密码
SmtpAddr = 'smtphz.qiye.163.com:25' # 邮件服务器
Host = 'smtphz.qiye.163.com' # 邮件服务器
To = [] # 邮件接收人