# cron 表达式 精确到秒 每天早上10点执行
Cron = ['0 0 6 * * *', '0 0 18 * * *']

# API服务
[Api]
Domain = ""
Port = 5050

# 爬虫
[Spider]
WebSite = "https://www.douban.com/group/szsh/discussion" # 定义爬取的网站
Cookie = ''
TimeLimit = 5 # 定义爬取的时间限制 /天

# 数据清洗
[DataClean]
BlackList = ["合租", "求", "找", "盐田", "龙岗", "坪山", "大鹏", "宝安", "光明", "单间", "一室", "一房", "女生"]

[Logger]
Level = "debug"
Formatter = "text"
Path = "logs/run.log"

# 通知
[Notice]
[Notice.WxPusher]
Enable = false #是否开启
AppToken = '' # 微信推送的AppToken
Uids = [] # 微信推送的UID
[Notice.Email]
Enable = true # 是否开启
From = '豆瓣房源爬虫 <notice@shroot.dev>' # 邮件发送人
User = 'notice@shroot.dev' # 邮箱账号
Pwd = '' # 邮箱密码
SmtpAddr = 'smtphz.qiye.163.com:25' # 邮件服务器
Host = 'smtphz.qiye.163.com' # 邮件服务器
To = [] # 邮件接收人