services:
  douban-rent-room:
    image: yazzyk/douban:${VERSION}
    build:
      dockerfile: ./Dockerfile
      context: ./
  douban-rent-room-latest:
    image: yazzyk/douban
    build:
      dockerfile: ./Dockerfile
      context: ./