version: '3.7'
services:
  douban:
    image: yazzyk/douban:latest
    container_name: douban
    volumes:
      - ${DOUBAN_ROOT}/config.toml:/app/config.toml
      - ${DOUBAN_ROOT}/nutsDB:/app/nutsDB
      - ${DOUBAN_ROOT}/logs:/app/logs
    ports:
      - '5050:5050'